server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: order-management
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: rider-management
          uri: http://localhost:8083
          predicates:
            - Path=/riders/**, 
        - id: egov-default-backend
          uri: http://localhost:8080
          predicates:
            - Path=/board/**, /auth/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order-management
          uri: http://orderManagement:8080
          predicates:
            - Path=/orders/**, 
        - id: rider-management
          uri: http://riderManagement:8080
          predicates:
            - Path=/riders/**, 
        - id: egov-default-backend
          uri: http://default-backend:8080
          predicates:        
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
